### ISSUE TITLE
Crash related to Rubracium Gauntlet on world creation

### ISSUE THREAD

**Issue by Twilix01** [Davoleo/Metallurgy-4-Reforged#100]
Just got this crash when I attempted to create a fresh world using the latest version of Metallurgy 4: Reforged, appears related to the new Rubracium Gauntlet as downgrading to the previous version still has this issue.

Crash report located here: https://pastebin.com/YU0u68Tt

**Comment by LordEpos** [comment]
This issue is still present in the current version. The only difference in the error message I'm getting, outside of various ID numbers which change with the other mods in the pack, is that instead of "PunchEffectProvider.java:32" mine says "PunchEffectProvider.java:43" Still crashes on world load :(

**Comment by Davoleo** [comment]
yeah that should be fixed for 0.2.2

**Comment by LordEpos** [comment]
Aight, thanks for working on it.
