### ISSUE TITLE
Be able to set dimension restrictions in the configuration.

### ISSUE THREAD

**Issue by kmirai88** [Davoleo/Metallurgy-4-Reforged#124]
The configuration in its current state does not allow for ore generation to be restricted to another dimension. In the original metallurgy 4, the config has an actual setting to restrict ores to a specific dimension to allow a sort of "progression".(an example of this would be to restrict fantasy ores to the twilight forest dimension).

I would like to see that option return so there is a more expansive way of setting up ores for modpacks that would contain your mod.

**Comment by HurtsAsHell** [comment]
We have so many other things to add and I don't see the usefulness of doing this, therefore, I will also talk about it with davoleo.

P.s.
sorry for the delay

**Comment by Davoleo** [comment]
We understand that this could be a nice feature for custom modpacks, 
but we're not going to add it in our mod mainly because it wouldn't be worth it in our opinions, 

we're happy to implement customizations and configurations for our mod, but I feel like this is a really specific feature that could be implemented with some great mods out there that offer completely custom features (i.e. Crafttweaker, Content Tweaker, COFH World, and many others....)

especially on 1.12.2 the mod panorama is really wide and you can do literally anything you think

So, by now I'll close this suggestion
With this I'm not closing to further discussion, so if you think there's a good reason for us to work on this  feature feel free to tell us what you think about it :)
