### ISSUE TITLE
Actually Additions Atomic Reconstructor Compatibility

### ISSUE THREAD

**Issue by Collecter128** [Davoleo/Metallurgy-4-Reforged#132]
Actually Additions has a thing called the Atomic Reconstructor which changes certain materials into other ones. Such as turning diamonds into Diamantine Crystals, or Iron into Enori Crystals. I asked the developer and it has the ability to work with other mods, but I don't think any other mods utilize this. I want to propose the possibility to you, but I also know you might not be interested.

Although not necessary, I think it would be an interesting addition for modpack makers who would find this materials useful for custom recipes.

**Comment by Davoleo** [comment]
mmh, are you talking about adding a new material for each material we have now in the mod, so that people can make it using the atomic reconstructor?

if that's what you're talking about then I think it's a bit too much for a mod integration, I mean AA integration is not a bad idea
but this would probably need further discussion

**Comment by Collecter128** [comment]
Maybe not every material. I just can’t think of any mods that add anything like this.

**Comment by Partonetrain** [comment]
For what it's worth, packmakers can already add Atomic Reconstructor recipes with ModTweaker.

https://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/ActuallyAdditions/AtomicReconstructor/

**Comment by Davoleo** [comment]
I'll close this, since by now I don't really see how it could be enhance player
Furthermore this kind of integration is usually done by modpack creators to alter normal gameplay
