### ISSUE TITLE
tiny and small piles of dusts metals and non-metals and Mekanism ore-processing support

### ISSUE THREAD

**Issue by kotelkonrad** [Davoleo/Metallurgy-4-Reforged#136]
^

**Comment by Davoleo** [comment]
Ok so I'm gonna explain the reasons why @HurtsAsHell closed this issue

1. Mekanism ore-processing support has been already added in this commit https://github.com/Davoleo/Metallurgy-4-Reforged/commit/ebfc835a288754f3d53c9a4c6f5d346a4d0aba82
2. as I wrote in #103 we're not going to add other utility items since JAOPCA already does it

_Side Note: as you can clearly see, when you create an issue there's some kind of template for you to compile, following it really helps us when fixing bugs or when discussing suggestions_
so we **reccomend** you to use it
