### ISSUE TITLE
Shields

### ISSUE THREAD

**Issue by ElasticKnife** [Davoleo/Metallurgy-4-Reforged#164]
Hi there,
First off, I would like to thank you developers for putting in the effort to bring back this mod.
I have one suggestion for a feature that I would love to see added.  With shields being added in as of the combat update, it would be great to see shields made out of Metallurgy materials, so as to complete the full aesthetic of the armour sets.  At the moment, it looks a bit strange to be holding a vanilla shield whilst wearing such cool, intricate armour.

Thanks again!

**Comment by Davoleo** [comment]
So, we'll have to think about this, our first idea was to introduce shields just for some materials more than for every material, so that we can have them all unique in their own way

thanks for bringing this discussion up, we'll give you further information about this later

in the meantime if you have more context and ideas about this feel free to post them here below, cause the way you suggested shields is quite generic, how would you like them to be implemented?

**Comment by MemedHams** [comment]
suggestion: have the late-game fantasy ores and alloys apply status effects to blocked melee enemies (tartarite could set enemies on fire, sanguinite could give a leaching effect that would convert some percentage of their attack into x seconds of regeneration, etc.)

**Comment by Davoleo** [comment]
We'll Implement:
- A black steel shield that does explosive damage #225 
- A tartarite shield that withers enemies
- A ignatius shield that sets enemies on fire
- A sanguinite shield that gives regeneration to the player when they're hit

**Comment by Davoleo** [comment]
Ok this is basically done
