### ISSUE TITLE
Construct's Armory armor values

### ISSUE THREAD

**Issue by SafsoufaS** [Davoleo/Metallurgy-4-Reforged#220]
I'm not sure if this is intentional or not but there are differing stats from metallurgy armors and Construct Armory's armors (addon to Tinker's Construct). For instance, a Promethium chest plate has an armor of 3 and toughness of .1, while on the other hand, the conarm equivalent has 2.4 armor and .84 toughness. 

I would like it so that the armor's stats match. I have contacted the conarm author and he stated that the stats are given by the maker of the metals. Is there a way to fix this? Unless this is intentional.

**Comment by Davoleo** [comment]
This is intentional, all TCon's tools and Conarm's armor sets have material stats a bit lowered for 2 reasons:
- Conarm Armor Sets, like TCon Tools are modular, can be repaired easily and can be further enhanced with traits and modifiers, while classic armor sets don't have that chance
- Also we don't want metallurgy to be considered just as a TCon/ConArm Addon, but more like a standalone mod that has its own full integration with those 2 mods

Due to this 2 reasons we lowered armor and tools stats to balance them, _however_ you still can change them thanks to additional tool mods like https://www.curseforge.com/minecraft/mc-mods/tweakers-construct

I'm gonna close this ticket now, if you have further questions feel free to reply below or to write on our discord server
