### ISSUE TITLE
Damascus Improvement

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#227]
**Describe the solution you'd like** <br>
So this metal is known for being tough and able to take anything you can throw at it so that's what I would do is make it mine like and iron pick but give it a durability like dimound or better. I might make the sword have a bleeding effect sort of like tinkers constructs steel so that way you foes feel the pain.
Lastly since there so tough they shouldn't have the penalty of if you use the pickaxe on wood it takes 2 durability instead of 1. these tools are supposed to be able to take anything you can throw at it as such they should be under the penalty of the normal tools although the should mine them any fast then normal because a pickaxe wasn't made to mine dirt.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
Even in vanilla if you use the wrong tool to mine a block the used durability is always 1, so the second suggestion is not doable.
Although I'll think about balancing the stats of tools

**Comment by chyper111** [comment]
Really? I thought that the chance for 1 damage was always 2 if you say use a pickaxe on dirt? Strange. even so this metals to common to make its effect supper amazing although maybe instead you could make a throwable knives which drop and can be picked up again. this could be another projectile that can trigger redstone or stay stuck in walls longer then arrows.

**Comment by SkyanUltra** [comment]
i feel like since damascus is known for its durability irl, it should have the traits Dense and Duritae on it, with dense being on the head/core for damascus parts, and Duritae coming with all of them. Along with that, buff the durability on the material itself and then you'll have a pretty good tinkers tool part that can be used in the case that you might be missing out on a bit of durability.

**Comment by Davoleo** [comment]
So, in the end, we decided to balance this metal according to its theme from #277 
We'll soon publish the first beta where you'll be able to test these changes, but if you're eager to test them you can also play on alpha.1 or alpha.2
anyways, I'm going to close this issue since most of the content has been covered.

---

> i feel like since damascus is known for its durability irl, it should have the traits Dense and Duritae on it, with dense being on the head/core for damascus parts, and Duritae coming with all of them

As for these tinker traits, I'll note them down and add them eventually
