### ISSUE TITLE
Crackpack 3 -- No way to smelt Mithril

### ISSUE THREAD

**Issue by Axtonion** [Davoleo/Metallurgy-4-Reforged#241]
There is no furnace (Including Tinker's Construct) That smelts mithril into a bar so it can be alloyed in Metallurgy-4-Reforged-0.2.3. Is this issue solved in a later version, or is there a mod that allows this metal to be smelted? Currently cannot make Haderoth or Quicksilver due to this problem

**Comment by Davoleo** [comment]
I have tested on 0.2.3 and I can't seem to reproduce this bug
I can process mithril just fine both in the vanilla furnace, the crusher and the smeltery

![image](https://user-images.githubusercontent.com/24458276/77964323-23ac7680-72df-11ea-9a15-d569e8833346.png)

![image](https://user-images.githubusercontent.com/24458276/77964294-1b543b80-72df-11ea-9ebd-c300585378f1.png)

![image](https://user-images.githubusercontent.com/24458276/77964275-15f6f100-72df-11ea-92d6-b766b00a0487.png)

**Comment by Axtonion** [comment]
Thats wild, my JEI wont even show me a recipe for mithril bars in Survival.
![No mithril](https://user-images.githubusercontent.com/62674376/77968115-c34c1380-72a3-11ea-964f-a47deef1b29c.png)

Below is what happens during my interactions with the crusher and different smelting methods in creative. Would you like me to send you my modpack for troubleshooting?

https://drive.google.com/open?id=1TGopGRPOsOjlweS52yvIRBNNe83CA4dv

**Comment by Davoleo** [comment]
in the gif you shared there was no fuel inside of the smeltery, although I don't what's going on with all the others processing methods 🤔 
I haven't seen Metallurgy in the original Crackpack 3 modpack, are you playing a modified version of it?
in that case it might be CraftTweaker removing some recipes automatically - you could check for that

**Comment by Axtonion** [comment]
So far Mithril is the only one I've found to do this. Any suggestions on how to check for something like this with CraftTweaker? I'm well acquainted with modding config files, but not with running scripts unfortunately. :( Also, the same thing definitely occurs in Tinker's smeltery, even with fuel--sorry for not showing that.

**Comment by Davoleo** [comment]
Ok I've tried installing Metallurgy on Crackpack 3 and I can confirm it's one of the crafttweaker scripts that hide and remove both the Mithril Ore from JEI and removes all the recipes for all the mithril stuff

You could play it under those conditions defined there, if you want to learn zenscript to fix the issue yourself, I'd suggest you the official CT docs (https://docs.blamejared.com/1.12/en/)
I've taken a quick look at the modpack scripts and I can say they're pretty complicated and not straight forwards since they use for loops and classes to automate some of the recipes removal

I could try to fix it when I have some spare time, but can't assure you I'll have some :P
