### ISSUE TITLE
Can't smelt vulcanite only have lava

### ISSUE THREAD

**Issue by Tigerdemigoddess** [Davoleo/Metallurgy-4-Reforged#243]
I literally have no hotter fuel as I have added these mods myself. So not part of a mod pack. The parts for vulcanite tools are in creative UI. But can't melt vulcanite with lava. An that's the hottest fuel I have.

**Comment by Davoleo** [comment]
you can use molten thermite as a hotter fuel

**Comment by Tigerdemigoddess** [comment]
How? I have no clue how to get nor create it?

**Comment by f-raZ0R** [comment]
you get molten thermite in your tinkers smeltery, by smelting thermite in it. You can craft thermite, with potash, sulfur, and... something else, I forgot what it was, but i know that you can definitely obtain it... oh wait, you have the vanilla recipe book, you can just check for the third thing there.

**Comment by Davoleo** [comment]
yeah exactly, by the way I strongly suggest you to use Just Enough Items, it really helps with recipes. @Tigerdemigoddess 
As I stated in #239 though I will add a new page to the wiki to explain the use of thermite a bit better
If anyone knows Markdown and wants to create a new page about it in the wiki they can do so because wiki editing is open to everyone
