### ISSUE TITLE
Config Option to Disable Certain Alloys

### ISSUE THREAD

**Issue by Sugarteeth** [Davoleo/Metallurgy-4-Reforged#249]
I'm looking for a way to disable the Metallurgy steel alloy :0 I'm currently assembling a modpack (mostly personal use), with progression tied to the ability to make steel for machines. Unfortunately, making it as easy as throwing manganese & iron together greatly upsets the balance of the other mods I have installed. I'd like there to be a config option to be able to turn off certain alloys, steel in my case.

**Comment by Davoleo** [comment]
You can do so with crafttweaker

**Comment by Sugarteeth** [comment]
I suppose :0 I was I was just thinking that it would be neat if you could do it without using other mods (additionally, I haven't figured out how to use crafttweaker >_>)

**Comment by Davoleo** [comment]
Well, on the other side you can tweak many more mods using crafttweaker, which is in my opinion a great tool to develop modpacks, so you might find some new great ways to tweak even more mods thanks to it instead of having this as a small scope feature only working on metallurgy alloys

I know just like every powerful tool it might be a bit hard to learn at first, but it's worth it in my opinion 

I'll also link some really useful resources to learn Crafttweaker:
The CT wiki: https://docs.blamejared.com/1.12/en/
Metallurgy related test script: https://github.com/Davoleo/Metallurgy-4-Reforged/blob/1.12.2/misc/ct_examples.zs

If you still can't figure out something / you want to ask some questions related to crafttweaker you can ask on:
Our Discord server: https://discord.gg/MFCdYDY
CT's Discord server: https://discord.blamejared.com/

**Comment by Davoleo** [comment]
closing this issue since the conversation seems to be resolved, if you're still having issues feel free to reply here or ask on one of the support servers I linked above
