### ISSUE TITLE
Equipping a resourcepack break the particles

### ISSUE THREAD

**Issue by sor1n** [Davoleo/Metallurgy-4-Reforged#251]
Whenever I have a resourcepack that also changes Metallurgy blocks, the particles seem to break from what they are supposed to be.

This happens in Minecraft 1.12.2, Metallurgy version 0.3.3

Screenshot with the issue at hand:

![2020-06-14_18 09 55](https://user-images.githubusercontent.com/923862/84599557-c26e5b00-ae6a-11ea-89a5-2c09b494cae0.png)

**Comment by Davoleo** [comment]
Does this happen with any resourcepack or is it this one in particular?

**Comment by sor1n** [comment]
It seems to be every resourcepack. I've tested even with just Jappa's Resource Pack and that still seems to happen (elthough different particles, but still broken)

**Comment by sor1n** [comment]
Ok, I've done further testing and, if you load a resource pack that doesn't change anything related to Metallurgy, everything is still ok. But if you load a resourcepack that does change a Metallurgy block, it breaks the particles.

Furthermore, if you unload it does fix it, so I'm not sure why previously it didn't. Maybe had something to do with me refreshing the pack. I can provide you my ResourcePack for further testing, if you wish.

**Comment by Klazkin** [comment]
@Davoleo, the custom textures in resource packs might somehow screw with the texture grid that Minecraft builds for all textures (including ones in metallurgy) on boot and messes up the offset values or whatever - so particles end up taking the wrong textures from memory, instead of them straight up missing completely.

When you reload assets in Minecraft, those _texture grids_ are rebuilt, which is why it might get fixed.

**Comment by sor1n** [comment]
> When you reload assets in Minecraft, those _texture grids_ are rebuilt, which is why it might get fixed.

Just to let you know, closing and reopening the game does not fix it. Loading the game with the pack loaded still keeps the particles broken

**Comment by Klazkin** [comment]
>Just to let you know, closing and reopening the game does not fix it. Loading the game with the pack loaded still keeps the particles broken

But pressing F3 + T (reload) fixes it though, with the resourcepack still active?

**Comment by sor1n** [comment]
> But pressing F3 + T (reload) fixes it though, with the resourcepack still active?

Nope, it does not

**Comment by Davoleo** [comment]
> @Davoleo, the custom textures in resource packs might somehow screw with the texture grid that Minecraft builds for all textures (including ones in metallurgy) on boot and messes up the offset values or whatever - so particles end up taking the wrong textures from memory, instead of them straight up missing completely.

iirc I'm building a custom Atlas Sprite which is the thing you're talking about there, and then assigning it as a particle texture programmatically, I'll have to investigate more to know the reason behind this texture issue.
I know that this issue is kind of similar to when I tried doing animated textures by changing the texture atlas once every 10ticks or so, you would get random particle texture also from other installed mods like mekanisms or minecraft textures themselves, again I have no idea why this might be happening 🤔

**Comment by Davoleo** [comment]
could you send me the resource pack on discord or here so I can playtest wether I've fixed the issue?

**Comment by sor1n** [comment]
Sure, what's your discord?

**Comment by Davoleo** [comment]
my user tag is Davoleo#3333, 
otherwise if you prefer, my server is http://discord.davoleo.net
