### ISSUE TITLE
Deep Iron Swimming Effect Inompatible with Idō Swimming

### ISSUE THREAD

**Issue by Kenja-mc** [Davoleo/Metallurgy-4-Reforged#253]
### General Information

**Describe the bug:**
When wearing the Deep Iron Armor, the player is unable to use Idō to swim, and ends up stuck in the water because they cannot swim out, even by holding space

**To Reproduce:**

1. Find a body of water and try swimming with Idō using `Ctrl`.
2. Put on a set of Deep Iron Armor
3. Repeat step 1, and notice how you are stuck in the water.

**Expected behavior:**

The player should be able to have the effects of the armor while underwater, and also swim quickly with the Idō mod. When wearing depth strider boots, the Idō mod functions as intended.
***

### Environment Versions

**Versions:**
- Metallurgy: 0.3.3
- Conflicting mod (if regarding mod integration): Idō
- Forge: 14.23.5.2854
- Minecraft: 1.12.2

***

### Additional Information
**Screenshots (if available):**
https://gfycat.com/ellipticalformalchrysalis

**Comment by Kenja-mc** [comment]
I forgot to mention that I am using `ido-1.12.2-1.1.0`.

**Comment by Davoleo** [comment]
mmh, I've watched the video you have uploaded, and that's also basically how deep iron armor works without having Idō installed
you're supposed to have infinite breath, night vision and fast underwater walking + step assist, however to balance it a bit (since it already is quite op to explore the seas) you can't go up in any way other than walking until the seaside or removing the armor

**Comment by Kenja-mc** [comment]
Is it intended that you cannot take off the armor while underwater?

**Comment by Davoleo** [comment]
I think it used to be like that in earlier versions, however you can remove it in the latest
