### ISSUE TITLE
Changing/Disabling Recipes for Nuggets

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [Davoleo/Metallurgy-4-Reforged#258]
**Describe the solution you'd like** <br>
As of the update that added the new decorative blocks and nuggets, I find many of my previous autocrafter recipes don't work anymore. This is because Metallurgy nuggets became the default output instead of what I had before (Thermal). Having the option to disable Metallurgy's nuggets, or changing the recipe (Maybe even using a machine?) would be beneficial.

**Why would you like this to be implemented?** <br>
This would help stop conflicts, and make it much easier for players like me who like adding Metallurgy to everything they play

**Additional context** (optional) <br>
Also one of the new Bronze decoration blocks is built the same as the Forestry sturdy casing which invalidated that recipe too, but I know that isnt something realisitc to tackle for you

**Comment by Davoleo** [comment]
I'll implement something similar with #259 
however as a temporary fix remember that you can use CraftTweaker to change / remove recipes
I'm excluding the implementation of a feature to change recipes specifically in Metallurgy because that would be useless since CraftTweaker is a really powerful tool you can use to do that
