### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#268]
**Describe the solution you'd like** <br>
What is you aim for projects? I could keep thowing ideas but I think it would be better to just ask what needs improvements and abiltys and where would you like suggestions? I don't wanna keep suggesting things you dont need.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
our aim with Metallurgy 4: Reforged is to make it a stable and complete mod
After implementing feature that have been suggested this mod will go in no-new features mode and we'll work full time on its spiritual successor which is "Metalworks 2" for newer versions of Minecraft

So feature-wise even now we're going to implement interesting gadgets and effects that are not overly complicated (by complicated I mean something that requires a bigger technic system behind [e.i. Energy upgrades for machines, different tier of machines, metal processing machines, features that require a whole new concept or dynamic behind it])
Other than that we're open to any kind of enhancement to current features to make them more interesting to players, although it has to be a thematic feature concerning a specific metal

actually I'd also be satisfied with implementing what has already been suggested till now, because I don't want this mod to have items that are useless to anyone but I don't want to bloat it with a bunch of random features.
So if you had some ideas in your mind that _you_ would like to see in the mod feel free to share them and we'll discuss about implementing them, although don't feel the need to continue suggesting new features, also because I'll have to move onto newer version sooner or later :P

**Comment by chyper111** [comment]
Ah thanks for the anwser.
