### ISSUE TITLE
 A New Minecart

### ISSUE THREAD

**Issue by chyper111** [Davoleo/Metallurgy-4-Reforged#270]
**Describe the solution you'd like** <br>
I would love to see a steam punkish minecart that works like a furnace cart but has an interface. Just something simple that can pull carts along with it and maybe your machines as well but personally this is just a cool want that i feel alot of mods bloat up "aka Railcraft" and not enough mods Touch on. Just and idea to consider.

**Why would you like this to be implemented?** <br>
Tell us about the reason(s) why you would implement this feature

**Additional context** (optional) <br>

**Comment by Davoleo** [comment]
I think most mods don't bother doing something like that because minecarts are really underused, but since our machines are, more or less vanilla-like, I think it'd be a neat feature

**Comment by Davoleo** [comment]
ok, first thing first, thanks for taking the time to write this.

at first glance I thought this was a neat idea

on second thought, I've done some research and knowing that minecart with machines integrated just serve as something that pushes carts, I first thought they were used like some sort of movable machines, but since they're only used as some sort of locomotive I think this goes a bit out of our scope as a mod, furthermore they're really underused because of the existance of Powered Rails that serve the same purpose
Railcraft probably adds something like that since it's a mod that is centered around minecarts

**Comment by chyper111** [comment]
Powered rails are both a rather annoying and also resource intensive for
those of us that like to avoid major metal duplication mods. I suggested
this because that feature is really under used and becuase the normal
tracks are very common. You find then everywhere. Also trains are much
cooler then one minecarts by themselves. Lastly railcraft has over bloated
a simple idea into a buggy unfinshed of what could have been. I like to
stick to simple when I pick mods and thats why I suggested this feature but
hay it was just that a suggestion. If I think of anything else i'll let you
know.
