### ISSUE TITLE
Interaction with lycanite pickaxes

### ISSUE THREAD

**Issue by KiwiSaysMeow** [Davoleo/Metallurgy-4-Reforged#298]
I was mining with a lycanite pickaxe and I saw 4 Rubracium and I mined it and only received 2, so I decided to test it out in my own world with creative.
Lycanite pickaxes come in 3 levels. So I put down 3 rows of every ore (1 row for each level of pickaxe) and mined it to see how much would drop.
 Level 1 pickaxe - All the ores gave 4/4 blocks except Adamantine, Rubracium, Atlarus, Carmot, Mithril, Orichalcum, Astral Silver and Lutetium. Those 8 I just mentioned dropped 2/4. 
Level 2 pickaxe - The results were the same as before except the 8 I mentioned now dropped 3/4 instead of 2/4.
Level 3 pickaxe: The results were the same as the Level 2 pickaxe results, the 8 ores still dropped 3/4. 
To Reproduce:
I have it all in the video I'm linking below, it's a few minutes long but it shows everything.
1. Create a lycanite pickaxe (level 1-3) 
2. Put down 4 ore blocks of Adamantine, Rubracium, Atlarus, Carmot, Mithril, Orichalcum, Astral Silver and Lutetium. 
3. Mine them. 
Expected behavior:
I expected it to drop 4/4 of the ore blocks, or at the very least, the higher tier ores would drop all 4 on the higher tier pickaxe.
Versions:
- Metallurgy: Metallurgy-4-Reforged-1.1.2
- Conflicting mod (if regarding mod integration): lycanitesmobs-1.12.2-2.0.7.2
- Other mods you think could cause issues:
- Forge: 1.12.2-forge-14.23.5.2854
- Minecraft: 1.12.2

![Pickaxe Level 1 Results](https://user-images.githubusercontent.com/75018084/100268711-65032d80-2f23-11eb-8732-4cb36c6f0429.png)
![Pickaxe Level 2 Results](https://user-images.githubusercontent.com/75018084/100268729-6af90e80-2f23-11eb-84bc-a95a40a4a3a3.png)
![Pickaxe Level 3 Results](https://user-images.githubusercontent.com/75018084/100268745-6e8c9580-2f23-11eb-8837-d3c785e89ab6.png)

**Comment by Davoleo** [comment]
so it looks like Lycanite Equipment partially fail to harvest blocks that have an harvest level higher than 3 (obsidian level)
There's probably some wrong logic in Lycanite's Mobs code since it works just fine with a TiCon Obsidian Pickaxe
As shown in this GIF:
https://cdn.discordapp.com/attachments/531161173694087188/787026488922079232/PvEYw79YN3.gif
Maybe try reporting it on their gitlab issues page here: https://gitlab.com/Lycanite/LycanitesMobs/-/issues

Also link this issue thread there you want
