### ISSUE TITLE
Crashing in multiplayer

### ISSUE THREAD

**Issue by zowner323** [Davoleo/Metallurgy-4-Reforged#307]
### General Information

**Describe the bug:**
When attacking or being attacked by a mob, the server crashes. Also delayed and unusual AI responses

**To Reproduce:**
1. Spawn a hostile mob
2. Let it attack you, or you attack it
3. Crash

**Expected behavior:**
Server crash/ buggy AI

***

### Environment Versions

**Versions:**
- Metallurgy: 1.2.3
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): private - dm

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
<script src="https://paste.ee/e/HizZ4/0"></script>

**Comment by Davoleo** [comment]
I can't reproduce the actual crash, but I can see what should've caused it, so I've just if-checked my way out of that edge case (LivingSetAttackTargetEvent shouldn't actually be fired for players since they don't have an AI)

I've also added another event that modifies the Visibility of the player to be 0 so that the event handler to disable mob's AI isn't called too frequently (should fix the AI jankiness)

I'll soon release a patch with this fix, when you have some time please tell me if this is still a thing or if it works fine
