### ISSUE TITLE
Crystal blocks require nuggets; when disabling nuggets, crystal blocks become unobtainable

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [Davoleo/Metallurgy-4-Reforged#321]
**Describe the solution you'd like** <br>
Would like a way to craft crystal blocks when nuggets are disabled. As it stands, disabling nuggets removes the recipe for crafting of any metallurgy-exclusive metal.

**Why would you like this to be implemented?** <br>
I have nuggets disabled to avoid conflict with other mods that add the common metals.

**Additional context** (optional) <br>
The crystal blocks that aren't metallurgy-exclusive are still craftable, as nuggets exist for those blocks thorugh other mods.

**Comment by Davoleo** [comment]
That behaviour is intended, it's also written in the comment above the entry to remove nugget recipes, I can't do anything to fix this, but if you want you can either disable nuggets from the other mods, otherwise change the recipes yourself via [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
