### ISSUE TITLE
flansmod vehicle bug?

### ISSUE THREAD

**Issue by DunkleDoug** [Davoleo/Metallurgy-4-Reforged#327]
when running metallurgy with flansmod there's a weird bug where vehicles from flans become comepletely useless, models don't show up and trying to get in seems to teleport you to 0,0 on the map, but not actually? the wheel shadows for the vehicle persist after the vehicle is broken and retreived too, which is very strange. i don't have the foggiest idea what's happening here but it makes me sad.
![2021-05-13_14 00 11](https://user-images.githubusercontent.com/77328663/118166524-9305fc80-b3f3-11eb-914e-dbce3cf78722.png)

**Comment by DunkleDoug** [comment]
that's almost certainly being caused by not having a content pack with an engine for the vehicle, installing the simple parts pack content pack for flansmod should rectify the crashing

**Comment by Davoleo** [comment]
So just to clarify, the mods I would need to install to reproduce this are:
- Flans Mod
- Custom NPCs
- Flans Mod Vehicles for Custom NPCs
- Simple Parts content pack for Flans Mod
- Metallurgy 4: Reforged 1.2.7

Once that's sorted out what do I need to do to cause this kind of issue?

**Comment by Evilerballon5** [comment]
Hello, the same thing happens to me, I want to play this great mod with Flan's mod, the crafting can be done, but the problem is that the texture of the vehicles disappears and leaves a circular shadow below, also, when mounting the vehicle, everything the map glitches disappearing completely and the vehicle cannot be controlled, to solve the map is to get out of the vehicle and restart the world.
![2021-05-25_17 41 28](https://user-images.githubusercontent.com/79736294/119577586-8c2aa280-bd80-11eb-8ae8-0fafbed4d639.png)
![2021-05-25_17 41 38](https://user-images.githubusercontent.com/79736294/119577589-8d5bcf80-bd80-11eb-9d07-e1ad73eeaa77.png)
![2021-05-25_17 41 45](https://user-images.githubusercontent.com/79736294/119577595-8df46600-bd80-11eb-9d48-abae50fda8b9.png)

**Comment by Evilerballon5** [comment]
I remove the mod and the problem is over. But this did not happen in 1.7.2 where it had another mod accompanying it, but they say it is no longer needed.
I give you the packages of Flan that I use in case you need it.
![M1](https://user-images.githubusercontent.com/79736294/119578255-cea0af00-bd81-11eb-9b0c-4551d52ff9ac.png)
![M2](https://user-images.githubusercontent.com/79736294/119578257-cf394580-bd81-11eb-8312-bad74f5bfdd3.png)
![M3](https://user-images.githubusercontent.com/79736294/119578258-cf394580-bd81-11eb-90c2-a1cc7052029e.png)
![2021-05-25_17 48 22](https://user-images.githubusercontent.com/79736294/119578285-d82a1700-bd81-11eb-8300-cfaf29a28f67.png)

**Comment by hollow-earth** [comment]
I have experienced the same problem. The only mods I have installed are Flan's Mod along with Metallurgy 4. For some reason, I get the exact same problem as OP.
