### ISSUE TITLE
[1.12.2] 'Cold-Snap' doesn't instantly harvest blocks with a harvest level of 0, despite what the tooltip says.

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#364]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 2
HadEnoughItems_1.12.2-4.21.1
Metallurgy-4-Reforged-1.3.4

---

![2022-08-06 22-09-38](https://user-images.githubusercontent.com/36653806/183273337-c23dc1cd-a0eb-41f9-9d9a-8e8b009f19b0.gif)

Cold-Snap's tooltip says that it should instantly harvest/break a block with a harvest level of 0, but it seems that it's not working or the pickaxe has a different effect that I'm not aware of. I tested this on Dirt, Sand and Wood and they weren't instantly harvested.

**Comment by Davoleo** [comment]
There's an issue in the tooltip description of that effect, Cold-Snap does affect blocks with harvest level of 0 but the block breaking tool still needs to be of the correct tool class to harvest the block efficiently, so for example sand and dirt would be instantly mined by shovel, or wood would be instantly harvested by the axe, or for the pickaxe the tinkers' tool forge apparently, I guess this effect can be kind of useless on the pickaxe since there are few to none blocks in vanilla that have pickaxe tool class and harvest level equals to 0

Looking at the gif though, I'd say the effect is working as intended

**Comment by Davoleo** [comment]
We've Decided to rework the effect making instantly harvest any block given that it is actually harvestable with the ceruclase tool and that the tool is the optimal tool to harvest said block,
Also updated the item tooltips to reflect the effect changes.
This way the effect should more straightforward and hopefully confuses players less, 
this also makes it behave less weirdly with other modded blocks that might have weird harvest levels like TiCon Tool forges
