### ISSUE TITLE
Crash with Chocolate Quest Repoured

### ISSUE THREAD

**Issue by Kasia1403** [Davoleo/Metallurgy-4-Reforged#371]
[crash-2023-02-03_09.12.54-server.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/10577433/crash-2023-02-03_09.12.54-server.txt)

**Comment by Kasia1403** [comment]
Tried to generate link to latest.log file via pastee, but it said "Request Entity Too Large".

**Comment by Kasia1403** [comment]
@Davoleo Could You help me even if I didn't fill-in issue template ? I don't like them. They are too complicated.

**Comment by Davoleo** [comment]
That doesn't seem like a problem caused by Metallurgy itself, the crash log mentions an NullPointerException thrown on line 81 of their "ProtectedRegionManager" which relies on chunk Capabilities to store information on these regions, but they don't check if the capability was retrieved successfully before using it 
([Reference](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/blob/1.12.2/src/main/java/team/cqr/cqrepoured/world/structure/protection/ServerProtectedRegionManager.java#L81))

Honestly I don't know much of ChunkProviders and worldgen stuff more than the basics, and I don't even know ChocolateQuest Structure and what they do with chunks to break when we try to generate our ores, but we haven't had any incompatibilities till now.
Maybe for some reason we are trying to generate ores in a position where there should be a chocolate quest structure..? even if that's the case though there's no way for me to tell and avoid this issue

you can try updating chocolate quest, maybe they've already fixed the issue if you already have the latest version available you can try contacting them and/or share this issue with them, although I've seen they don't seem to support 1.12.2 anymore so, we 'll have to see how they react to this

It might also be the case I'm overlooking something really stupid on my side, if that's the case, someone please tell me and I'll act accordingly

**Comment by Kasia1403** [comment]
What to do if they ( CQR authors ) blocked me on their Github ?

**Comment by Kasia1403** [comment]
Sorry, but it must be Metallurgy 4 Reforged 1.3.6 fault, because I checked modpacks containing theese 2 mods and in last updated modpack ( SHIMMER ) Metallurgy 4 Reforged version is 1.3.5 and CQR version is the same as mine ( 2.6.12B ).

**Comment by Kasia1403** [comment]
@Davoleo Could You give me a links to working and not conflicting Metallurgy 4 Reforged and Chocolate Quest Repoured mods versions that will 100 % work together and will not have this buggy code NullPointerException thrown on line 81 of their "ProtectedRegionManager" ?

**Comment by Kasia1403** [comment]
I found another strange thing : when trying to pregenerate a new world it's Nyx ROTN mod crashing like this:

[crash-2023-02-05_14.30.01-server.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/10611159/crash-2023-02-05_14.30.01-server.txt)

**Comment by Davoleo** [comment]
> What to do if they ( CQR authors ) blocked me on their Github ?

sorry, but I can't help you with that

> @Davoleo Could You give me links to working and not conflicting Metallurgy 4 Reforged and Chocolate Quest Repoured mods versions that will 100 % work together and will not have this buggy code causing NullPointerException thrown on line 81 of their "ProtectedRegionManager" ?

Short answer is no, 
The reason is: I don't know when they introduced that bug or anything about the changelog of Chocolate quests on any version, I would have to go through all the history of the file and comparing the dates with the actual curseforge releases dates, also taking possible release publishing delay into account, and then find which release was the one that added the problematic commit.

> I found another strange thing : when trying to pregenerate a new world it's Nyx ROTN mod crashing like this:

That seems like it's caused by a different thing, not sure how this crash is related to that

All that aside this _could be a retrogenereation incompatibility_ with CQR, which would be a first time an incompatibility with the retrogen system comes up, can you try turning it off in M4R configuration files and report the outcome? File is `config/metallurgy_reforged/worldgen.cfg`, config entry name is `Retrogen`

**Comment by Kasia0314** [comment]
Looks like turning off retrogen helped.
