### ISSUE TITLE
Ruins Mod Crash

### ISSUE THREAD

**Issue by Neoslayer** [Davoleo/Metallurgy-4-Reforged#377]
I would hope this would be helpful, but I do not mind if nothing is done about this. After all, I loaded a JEID world without the mod not realizing I have done that, resulting in a catastrophic mess, and for all I know this crash could be a result of it.
[Crash.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/11948955/Crash.txt)

**Comment by Davoleo** [comment]
mmh, the crash is indeed a weird one, usually should just happens if you use invalid values as minY and maxY coords in the worldgen config, first thing that comes to my mind is that when downgrading to a previous version of the mod, you kept new worldgen config files with an old mod version `1.3.0-alpha.2` where the worldgen was structured very differently and didn't allow a `minY > maxY` to generate the ores outside of the `[minY..maxY]` range [useful for nether ores].

While I wouldn't recommend to play on an alpha version of the mod, if you need to wait for me to fix #376 , be sure to make a backup of the world and after checking Shadow Iron minY and maxY in the config if you see the condition I wrote above is not respected remove the `metallurgy_reforged` config folder completely to regenerate the mod configuration

_One Last Note_: if you configured the mod for a newer version and you want to keep your modified config be sure to backup the config folder as well before deleting it so you can restore it once you update the mod again later.

**Comment by Davoleo** [comment]
Assuming this is resolved.
