### ISSUE TITLE
Spartan's Weaponry integration oversight

### ISSUE THREAD

**Issue by Beeflauncher** [Davoleo/Metallurgy-4-Reforged#381]
### General Information

While testing update 1.4.0, I noticed a slight oversight with weapons that are based off of materials with unique swinging speeds(eg: platinum, quicksilver, ignatius, etc). Their attack speeds seem to be the same as weapons without unique attack speeds.

That's really all.

**Comment by Davoleo** [comment]
This is because SpartanWeaponry's own ToolMaterial system doesn't support attack speed unlike ours, so stats like that are not integrated directly.
SpartanWeaponry API to create items doesn't seem to support changing their attributes so the possible solutions to this would be:
- creating subclasses for all spartan tool types and initializing weapons from those classes, there I would have a more fine-grained control and I could implement attack speed the same way it was implemented in the original mod (this would pollute the codebase a lot for such a small enhancement)
- Creating a custom property called Attack Speed with a callback on the item update method and add the attack speed modifier directly to the itemstack (with the compromise that it would probably only show up when you create the actual weapon, probably)

Adding even more to this developing integration for SpartanWeaponry can take a lot of time, since SpartanWeaponry on the latest version uses Mixins to implement certain features, which renders the mod incompatible with my dev environment since I'm currently using really old toolchain (ForgeGradle 2.3), this means I need to test on an older version of the mod and to test things on the latest I need to first compile the mod and test externally increasing dev times greatly.
Both solutions are not really enticing due to the reasons mentioned above, so, at least for the moment and until I may upgrade the project toolchain this won't be implemented.
