### ISSUE TITLE
Ore generation info & wiki revision

### ISSUE THREAD

**Issue by Jmbkpo** [Davoleo/Metallurgy-4-Reforged#61]
I'm asking if you guys could please bring to the wiki info about the layer spawn of the ores (if exist a specific level) or make the ores spawn in specific layers so we can no only guide ourselves but testing if the spawnrates are balanced, give it realism, etc.

**Comment by Davoleo** [comment]
I'm doing a grammar and structure revision of the wiki pages when I have time

I've begun with: https://github.com/Davoleo/Metallurgy-4-Reforged/wiki/Custom-Armor-Effects
and https://github.com/Davoleo/Metallurgy-4-Reforged/wiki/Custom-Tools-Effects

I also generalized the sword section to be the tools section, since pickaxe and other tools are going to have some effects aswell

**Comment by HurtsAsHell** [comment]
[Ore Generation in Wiki](https://github.com/Davoleo/Metallurgy-4-Reforged/wiki/Ore-Generation)
@Jmbkpo
